### ISSUE TITLE
Correção Testes [2h]

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#1]
Equipe: **Testes**
Objetivo: Fazer as solicitações passadas no feedback do último trabalho.
Limite: 12/11/2020 - 15:00

**Comment by souzavdj** [comment]
Essa issue foi resolvida atualizando as descrições de casos de usuário na [Wiki](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki) do git.
