### ISSUE TITLE
[PSW] Matriz CRUD [2h]

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#10]
Equipe: **PSW**
Objetivo: Definir e montar uma [matriz CRUD](https://pt.wikipedia.org/wiki/Matriz_de_intera%C3%A7%C3%B5es)
Limite: 05/11/2020 - 15:00
Feedback:
> Matriz CRUD, não fizeram – nota inalterada

**Comment by Diegobrvt** [comment]
Feito => https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Matriz-CRUD

**Comment by Diegobrvt** [comment]
Horas gastas 1/2 hora

**Comment by zirondi** [comment]
Diego -> HH= 1/2h
