### ISSUE TITLE
Casos de Testes de Aceitação [12h]

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#2]
Equipe: **Testes**
Objetivo: Passar de especificação dos testes de aceitação para os casos de teste de aceitação, para isto precisarão incluir os dados que serão usados em cada caso de teste. A equipe de PSW definirá os domínios dos campos.
Limite: 12/11/2020 - 15:00
Artefato: [Casos de Teste de Aceitação](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/tree/main/front-end/docs/Casos%20de%20Teste%20de%20aceita%C3%A7%C3%A3o)

**Comment by souzavdj** [comment]
Issue resolvida na pasta [Teste de aceitaçao](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/tree/main/front-end/docs/Casos%20de%20Teste%20de%20aceita%C3%A7%C3%A3o) onde se encontra todos os arquivos .features.
