### ISSUE TITLE
[PSW] Implementação da tela T06 - Tela de Leitura de Notas, com o back mockado 

### ISSUE THREAD

**Issue by igorgs-rj** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#20]
Equipe: PSW 
Objetivo: Implementação da tela T06 - Tela de Leitura de Notas, com o back mockado 

Limite: 26/11/2020 - 15:00 
Artefato:  
Feedback: 

Horas Estimadas: 1,3 

Horas Gastas:

**Comment by Diegobrvt** [comment]
Aguardando feedback @zirondi

**Comment by Diegobrvt** [comment]
Horas parciais:
domingo 14h-2h
segunda 10h-15h
terça 09:00 - 16h & 19h -00h

**Comment by Diegobrvt** [comment]
Diego ->
domingo 14h - 2h
segunda 10h - 15h
terça 09h - 16h & 19h - 00h
quarta 09h - 12h & 13h-17h
Leandro ->
domingo 14h - 2h
segunda 10h - 15h
terça 09:00 - 16h & 19h - 00h
quarta 13h - 00h
quinta ?
