### ISSUE TITLE
[PSW] Estilização do front com css responsivo 

### ISSUE THREAD

**Issue by igorgs-rj** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#26]
Equipe: PSW 
Objetivo: Estilização do front com css responsivo 

Limite: 26/11/2020 - 15:00 
Artefato:  
Feedback: 

Horas Estimadas: 1,3 

Horas Gastas:

**Comment by Diegobrvt** [comment]
Aguardando feedback @zirondi

**Comment by Diegobrvt** [comment]
Horas parciais:
domingo 14h-2h
segunda 10h-15h
terça 09:00 - 16h & 19h -00h

**Comment by Diegobrvt** [comment]
Responsividade realizada nas telas 01,02,03,04,05

**Comment by zirondi** [comment]
Diego -> 
domingo 14h-2h
segunda 10h-15h
terça 09:00 - 16h & 19h -00h
Leandro ->
domingo 14h-2h
segunda 10h-15h
terça 09:00 - 16h & 19h -00h

**Comment by Diegobrvt** [comment]
Diego ->
domingo 14h - 2h
segunda 10h - 15h
terça 09h - 16h & 19h - 00h
quarta 09h - 12h & 13h-17h
Leandro ->
domingo 14h - 2h
segunda 10h - 15h
terça 09:00 - 16h & 19h - 00h
quarta 13h - 00h
quinta ?
