### ISSUE TITLE
[Testes] Medição da cobertura dos testes de aceitação [2h]

### ISSUE THREAD

**Issue by igorgs-rj** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#38]
Equipe: Testes 
Objetivo: Medição da cobertura dos testes de aceitação 

Limite: 26/11/2020 - 15:00 
Artefato:  
Feedback: 

Horas Estimadas: 2,7 

Horas Gastas:

**Comment by deniscrispe** [comment]
Denis - 2 hora - 26/11
