### ISSUE TITLE
 [Testes] Criação dos casos de teste de defeito [2h]

### ISSUE THREAD

**Issue by igorgs-rj** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#39]
Equipe: Testes 
Objetivo: Criação dos casos de teste de defeito 

Limite: 26/11/2020 - 15:00 
Artefato:  
Feedback: 

Horas Estimadas: 2,7 

Horas Gastas:

**Comment by deniscrispe** [comment]
Denis - 1 hora - 23/11
Denis - 1 hora - 24/11

**Comment by viisantos** [comment]
Vitória
24/11 - revisão de conteúdo - 2h
25/11 - revisão de conteúdo - 2h
26/11 - Implementação dos testes de aceitação e de defeito - 10h

**Comment by g1234odoy** [comment]
Fernando - 1.5 hora - 24/11
Fernando - 1 hora - 25/11

**Comment by souzavdj** [comment]
Vinicius - 1 hora - 24/11
Vinicius - 1 hora - 25/11
