### ISSUE TITLE
Novos Casos de Testes

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#4]
Equipe: **Testes**
Objetivo: Produzir novos casos de teste caso surjam novas funcionalidades/perfis de acesso em **PSW**.
Limite: 12/11/2020 - 15:00

**Comment by viisantos** [comment]
Na verdade, nós fizemos alguns ajustes nas especificações, para levá-los aos casos de Teste. Removemos mais do que adicionamos.
