### ISSUE TITLE
[PSW] - Frontend (Pasta)

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#45]
Primeiramente Fazer o HTML básico da tela:
- [ ] [Folder](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/blob/main/front-end/docs/Guia_de_ids/10-Folder.png)

Depois integrar CRUD com backend mockado:
- [ ] Criar Pasta
- [ ] Listar Pasta
- [ ] Editar Pasta
- [ ] Apagar Pasta

**Comment by zirondi** [comment]
Fechando pelo change scope request aceito.
