### ISSUE TITLE
Correção PSW [4h]

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#5]
Equipe: **PSW**
Objetivo: Fazer as alterações solicitadas na interação anterior.
Limite: 10/11/2020 - 15:00

**Comment by Diegobrvt** [comment]
*A equipe de testes não viu a exclusão da pasta no protótipo 

Devemos criar um área de administração das pastas de arquivos

**Comment by Diegobrvt** [comment]
Feito
