### ISSUE TITLE
[PSW] - Backend (Pasta)

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#53]
Programação do gerenciamento de pastas no Backend:
- [ ] Criar Pastas
- [ ] Listar Pastas
- [ ] Atualizar Pastas
- [ ] Deletar Pastas

**Comment by zirondi** [comment]
Esse mal tem tempo pq foi mais repetição de código vindo do back-end de notas, de qqlr jeito

https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/blob/main/back-end/src/routes/folderRoutes.js

**Comment by zirondi** [comment]
Fechando pelo change scope request aceito.
