### ISSUE TITLE
[PSW] Domínio dos Campos [2h]

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#6]
Equipe: **PSW**
Objetivo: Definir os domínio dos campos (faixa de valores válidos e inválidos)
Limite: 10/11/2020 - 15:00
Artefato: [planilha de campos e ids](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/blob/main/front-end/docs/Guia_de_ids/Lista_de_Ids.xlsx)
Feedback: Entregar via Wiki

**Comment by Diegobrvt** [comment]
Feito

**Comment by zirondi** [comment]
Link da planilha:
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/blob/main/docs/Guia_de_ids/Lista_de_Ids.xlsx

**Comment by Diegobrvt** [comment]
Feito e corrigido na área do wiki : https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Wireframe

**Comment by Diegobrvt** [comment]
Horas gastas : 2h

**Comment by zirondi** [comment]
Diego -> HH= 2h
