### ISSUE TITLE
[Arquitetura] - Levantamento de arquitetura

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#61]
Realizar o levantamento de arquitetura *as-is*:
- [ ] Incluir padrões arquiteturais
- [ ] Incluir estilos arquiteturais

**Comment by DevGabrielDeSouza** [comment]
Expectativa de horas a serem gastas: 6 horas

**Comment by merlid** [comment]
Expectativa de horas a serem gastas: 5 horas

**Comment by merlid** [comment]
Quantidade de horas gastas até agora: 7 horas

**Comment by nathaliagomes** [comment]
Registro de horas gastas na documentação:

12/12: 20:00 às 22h20 (2h20)
13/12: 19:00 às 20:00 (1h)
16/12: Aula de APS 
18/12: 18h45 às 22:30 (3h45)
19/12: 13h30 às 16:05 (2h35), reunião sobre o projeto 21:10 às 22:24 

Até o momento: cerca de 9 horas

**Comment by RamonBoucas** [comment]
expectativa de horas a serem gastas : 6 horas
quantidade de horas efetivamente gastas: 7 horas

**Comment by merlid** [comment]
> Quantidade de horas gastas até agora: 7 horas

Atualização: 9 horas gastas

**Comment by RamonBoucas** [comment]
Atualização 9 horas gastas

**Comment by nathaliagomes** [comment]
Atualização:
20/12: 14:30 às 23:35 (9h)

Total de horas gastas na documentação da arquitetura: cerca de 18 horas

**Comment by DevGabrielDeSouza** [comment]
Atualização: 10 horas foram gastas na tarefa.

**Comment by nathaliagomes** [comment]
Levantamento de arquitetura: https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Arquitetura-As-Is

**Comment by cassiofb-dev** [comment]
feito
