### ISSUE TITLE
[Arquitetura] - Sugestão de arquitetura

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#62]
Realizar a sugestão de arquiterua *to-be*:
- [ ] Incluir padrões arquiteturais
- [ ] Incluir estilos arquiteturais
- [ ] Documentar decisões
- [ ] Justificar decisões

**Comment by DevGabrielDeSouza** [comment]
Expectativa de horas a serem gastas: 6 horas

**Comment by merlid** [comment]
Expectativa de horas a serem gastas: 5 horas

**Comment by merlid** [comment]
Quantidade de horas gastas até agora: 7 horas

**Comment by RamonBoucas** [comment]
Expectativa de horas a serem gastas: 5 horas 
Horas gastas até aqui : 6 horas

**Comment by merlid** [comment]
> Quantidade de horas gastas até agora: 7 horas

Atualização: 9 horas gastas

**Comment by RamonBoucas** [comment]
Atualização 8 horas gastas

**Comment by DevGabrielDeSouza** [comment]
Atualização: 9 horas foram gastas na tarefa.

**Comment by nathaliagomes** [comment]
Registro de horas gastas na documentação (Levantamento e Sugestão):

12/12: 20:00 às 22h20 (2h20)
13/12: 19:00 às 20:00 (1h)
16/12: Aula de APS
18/12: 18h45 às 22:30 (3h45)
19/12: 13h30 às 16:05 (2h35), reunião sobre o projeto 21:10 às 22:24
20/12: 14:30 às 23:35 (9h)

Total de horas gastas na documentação: cerca de 18 horas

**Comment by nathaliagomes** [comment]
Sugestão de arquitetura: https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Arquitetura-To-Be

**Comment by cassiofb-dev** [comment]
feito
