### ISSUE TITLE
[Gestão] - Gerenciamento do Burndown Chart

### ISSUE THREAD

**Issue by igorgs-rj** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#65]

**Comment by dasope** [comment]
https://teams.microsoft.com/l/file/0AB9A2B8-BD2A-40CA-BE8B-080131F08021?tenantId=8eeca404-a47d-4555-a2d4-0f3619041c9c&fileType=xlsx&objectUrl=https%3A%2F%2Fcefetrjbr.sharepoint.com%2Fsites%2FTI-Grupo4%2FDocumentos%20Compartilhados%2FGeneral%2FSprint%203%2FBurndown.xlsx&baseUrl=https%3A%2F%2Fcefetrjbr.sharepoint.com%2Fsites%2FTI-Grupo4&serviceName=teams&threadId=19:d257eeb86deb41afb6374be0eeecc68a@thread.tacv2&groupId=cb12fc2b-d5f8-48ac-b693-ec3e41462e7b

**Comment by igorgs-rj** [comment]
https://teams.microsoft.com/l/file/0AB9A2B8-BD2A-40CA-BE8B-080131F08021?tenantId=8eeca404-a47d-4555-a2d4-0f3619041c9c&fileType=xlsx&objectUrl=https%3A%2F%2Fcefetrjbr.sharepoint.com%2Fsites%2FTI-Grupo4%2FDocumentos%20Compartilhados%2FGeneral%2FSprint%203%2FBurndown.xlsx&baseUrl=https%3A%2F%2Fcefetrjbr.sharepoint.com%2Fsites%2FTI-Grupo4&serviceName=teams&threadId=19:d257eeb86deb41afb6374be0eeecc68a@thread.tacv2&groupId=cb12fc2b-d5f8-48ac-b693-ec3e41462e7b
