### ISSUE TITLE
[PSW] Matriz de Perfis [1h]

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#7]
Equipe: **PSW**
Objetivo: Definir a matriz perfil x funcionalidade e verificar as alterações de tela.
Limite: 10/11/2020 - 15:00
Artefato: [Matrix de Perfis](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Matriz-Perfil-x-Funcionalidade)
Feedback:
> Matriz perfil x funcionalidade. É difícil  imaginar um sistema que só tenha um perfil de usuário. Geralmente é necessário um perfil de Administrador para tarefas de gestão de usuários, como: Perdi acesso ao meu e-mail, como recupero minha senha? Acho que vocês deveriam considerar incluir um perfil de admin.

**Comment by Diegobrvt** [comment]
Feito.
[https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Matriz-Perfil-x-Funcionalidade](url)

**Comment by zirondi** [comment]
https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Matriz-Perfil-x-Funcionalidade

**Comment by Diegobrvt** [comment]
Horas gastas: 1h

**Comment by zirondi** [comment]
Diego -> HH= 1h
