### ISSUE TITLE
[Testes] - Implementar os Testes Unitários (Login)

### ISSUE THREAD

**Issue by igorgs-rj** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#80]

**Comment by deniscrispe** [comment]
[https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/commit/0ed183a96d6fe1f543c6300c98955769727e76e9](url)

**Comment by deniscrispe** [comment]
![Evidência](https://i.ibb.co/zFJBfjM/Login1.png)
