### ISSUE TITLE
[Testes] - Implementar os Testes Unitários (Cadastro)

### ISSUE THREAD

**Issue by igorgs-rj** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#81]

**Comment by deniscrispe** [comment]
[https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/commit/c703fcb9866ae3d85fb5397bc523c59abef60d49](url)

**Comment by deniscrispe** [comment]
![Evidência](https://ibb.co/cXSQMH4)
