### ISSUE TITLE
[Arquitetura] - Ajustes na Documentação

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#87]
Ajustes na documentação segundo ao feedback:
>- No diagrama de componentes de vocês existem setas sólidas e setas pontilhadas, mas não existe explicação da semântica delas. Se for dependência (chamdas) para pontilhada e associação (atributos) para sólidas, como na UML, o formato das pontas de seta estão errados e também o sentido delas. Por exemplo, é o back-end que chama o front-end? acho que vocês precisam revisar a notação de diagrama de componentes.
>- No diagrama de pacotes também aparecem diversos pacotes soltos, sem setas, o sentido e semântica das setas está duvidoso também.
>- As camadas aparecem bem caracterizadas. Possivelmente teríamos subdivisões destas camadas, mas não é um problema.
>- O diagrama de comunicação está puramente conceitual, não aparece componentes reais do sistema na interações, não permitindo a compreensão da interação entre eles.
>- Não teve efetivamente sugestão de melhoria na arquitetura, apesar desta estar bem simples, dificulta o entendimento dela a falta de funcionalidaes prontas (hoje temos somente login e signup) e a falta de representação destas funcionalidades prontas na arquitetura.
>- Minha sugestão para vocês é melhorar os diagramas para que eles reflitam a realidade e os componentes reais da aplicação, daí vocês poderão identificar oportunidades de melhoria na arquitetura.

**Comment by DevGabrielDeSouza** [comment]
Expectativa de horas a serem gastas:
20hrs

**Comment by nathaliagomes** [comment]
Expectativa de horas a serem gastas: 22 horas

Registro:
28/12: 17h45 - 22h10. Corrigi as setas e seus respectivos sentidos do "Diagrama de Pacotes: Arquitetura As-Is" e atualizei na Wiki do projeto.

**Comment by merlid** [comment]
Horas gastas até agora: 7h

**Comment by merlid** [comment]
Entregáveis: 

[Arquitetura As-Is (sprint 2) atualizada](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Arquitetura-As-Is)

[Arquitetura To-Be (sprint 2) atualizada](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Arquitetura-To-Be)

**Comment by RamonBoucas** [comment]
Horas gastas até o momento : 9 horas

**Comment by DevGabrielDeSouza** [comment]
Foram gastas 19hrs na tarefa.

**Comment by nathaliagomes** [comment]
Quantidade de horas gastas nessa tarefa: 22 horas
