### ISSUE TITLE
[Arquitetura] - Verificação do Código Fonte

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#88]
Verificar se os ajustes de arquitetura foram feitos nos códigos do [frontend](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/tree/main/front-end) e [backend](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/tree/main/back-end)

**Comment by RamonBoucas** [comment]
Horas gastas até o momento 6 horas

**Comment by merlid** [comment]
Horas Gastas até o momento: 10h

**Comment by merlid** [comment]
Entregável: 

[Verificação dos ajustes de arquitetura no código fonte](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/Verifica%C3%A7%C3%A3o-dos-ajustes-de-arquitetura-no-c%C3%B3digo-fonte)

**Comment by nathaliagomes** [comment]
Horas gastas nessa tarefa: 4 horas
