### ISSUE TITLE
[Arquitetura] - Apoio ao Projeto

### ISSUE THREAD

**Issue by cassiofb-dev** [dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4#89]
- Apoio ao projeto de requisitos não funcionais com definição de táticas factíveis para atender
estes (performance, segurança e confiabilidade). Utilizar o catálogo do Rosanski e Woods.
- Explicar quais táticas foram escolhidas e como foram implementadas.

**Comment by merlid** [comment]
Horas gastas até o momento: 4 horas

**Comment by merlid** [comment]
Entregável: 

[Táticas de Apoio ao Projeto de Requisitos Não Funcionais](https://github.com/dsm-cefet-rj/trabalho-integrado-2020-1-grupo-4/wiki/T%C3%A1ticas-de-Apoio-ao-Projeto-de-Requisitos-N%C3%A3o-Funcionais)

**Comment by RamonBoucas** [comment]
Horas gastas até o momento: 4 horas

**Comment by DevGabrielDeSouza** [comment]
Foram gastas 4 horas na tarefa.

**Comment by nathaliagomes** [comment]
Horas gastas nessa tarefa: 4 horas
